(require-package 'monokai-theme)
(require-package 'color-theme-sanityinc-tomorrow)
(require-package 'cherry-blossom-theme)
(require-package 'busybee-theme)
(require-package 'gruber-darker-theme)
(require-package 'afternoon-theme)
(require-package 'cyberpunk-theme)
(require-package 'moe-theme)
(require-package 'alect-themes)
(require-package 'ample-theme)

;;(load-theme 'monokai t)
(require 'moe-theme)
;;(require 'moe-dark-theme)
(require 'alect-black-alt-theme)
;;(require 'moe-theme-switcher)
(provide 'init-theme)
